package actions

import (
	"fmt"
	"net/http"
	"time"

	"github.com/bigpanther/trober/models"
	"github.com/gobuffalo/buffalo"
	"github.com/gobuffalo/nulls"
	"github.com/gobuffalo/pop/v5"
	"github.com/gofrs/uuid"
)

// This file is generated by Buffalo. It offers a basic structure for
// adding, editing and deleting a page. If your model is more
// complex or you need more than the basic implementation you need to
// edit this file.

// Following naming logic is implemented in Buffalo:
// Model: Singular (Customer)
// DB Table: Plural (customers)
// Resource: Plural (Customers)
// Path: Plural (/customers)
// View Template Folder: Plural (/templates/customers/)

// customersList gets all Customers. This function is mapped to the path
// GET /customers
func customersList(c buffalo.Context) error {
	var loggedInUser = loggedInUser(c)
	if !loggedInUser.IsAtleastBackOffice() {
		return c.Render(http.StatusNotFound, r.JSON(models.NewCustomError(notFound, fmt.Sprint(http.StatusNotFound), errNotFound)))
	}
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return models.ErrNotFound
	}

	customers := &models.Customers{}

	// Paginate results. Params "page" and "per_page" control pagination.
	// Default values are "page=1" and "per_page=20".
	q := tx.PaginateFromParams(c.Params())

	// Retrieve all Customers from the DB
	if err := q.Scope(restrictedScope(c)).Order(orderByCreatedAtDesc).All(customers); err != nil {
		return err
	}

	return c.Render(200, r.JSON(customers))

}

// customersShow gets the data for one Customer. This function is mapped to
// the path GET /customers/{customer_id}
func customersShow(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return models.ErrNotFound
	}

	// Allocate an empty Customer
	customer := &models.Customer{}

	// To find the Customer the parameter customer_id is used.
	if err := tx.Scope(restrictedScope(c)).Find(customer, c.Param("customer_id")); err != nil {
		return c.Error(http.StatusNotFound, err)
	}

	return c.Render(200, r.JSON(customer))

}

// customersCreate adds a Customer to the DB. This function is mapped to the
// path POST /customers
func customersCreate(c buffalo.Context) error {
	var loggedInUser = loggedInUser(c)
	if !loggedInUser.IsAtleastBackOffice() {
		return models.ErrNotFound
	}
	// Allocate an empty Customer
	customer := &models.Customer{}

	// Bind customer to the html form elements
	if err := c.Bind(customer); err != nil {
		return err
	}

	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return models.ErrNotFound
	}

	if !loggedInUser.IsSuperAdmin() || customer.TenantID == uuid.Nil {
		customer.TenantID = loggedInUser.TenantID
	}
	customer.CreatedBy = nulls.NewUUID(loggedInUser.ID)
	customer.CreatedAt = time.Now().UTC()
	customer.UpdatedAt = time.Now().UTC()

	// Validate the data from the html form
	verrs, err := tx.ValidateAndCreate(customer)
	if err != nil {
		return err
	}

	if verrs.HasAny() {
		return c.Render(http.StatusUnprocessableEntity, r.JSON(verrs))
	}

	return c.Render(http.StatusCreated, r.JSON(customer))

}

// customersUpdate changes a Customer in the DB. This function is mapped to
// the path PUT /customers/{customer_id}
func customersUpdate(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return models.ErrNotFound
	}

	// Allocate an empty Customer
	customer := &models.Customer{}

	if err := tx.Scope(restrictedScope(c)).Find(customer, c.Param("customer_id")); err != nil {
		return c.Error(http.StatusNotFound, err)
	}

	// Bind Customer to the html form elements
	if err := c.Bind(customer); err != nil {
		return err
	}
	customer.UpdatedAt = time.Now().UTC()

	verrs, err := tx.ValidateAndUpdate(customer)
	if err != nil {
		return err
	}

	if verrs.HasAny() {
		return c.Render(http.StatusUnprocessableEntity, r.JSON(verrs))
	}

	return c.Render(http.StatusOK, r.JSON(customer))

}

// customersDestroy deletes a Customer from the DB. This function is mapped
// to the path DELETE /customers/{customer_id}
func customersDestroy(c buffalo.Context) error {
	var loggedInUser = loggedInUser(c)
	if !loggedInUser.IsAtleastBackOffice() {
		return c.Render(http.StatusNotFound, r.JSON(models.NewCustomError(notFound, fmt.Sprint(http.StatusNotFound), errNotFound)))
	}
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return models.ErrNotFound
	}

	// Allocate an empty Customer
	customer := &models.Customer{}

	// To find the Customer the parameter customer_id is used.
	if err := tx.Scope(restrictedScope(c)).Find(customer, c.Param("customer_id")); err != nil {
		return c.Error(http.StatusNotFound, err)
	}

	if err := tx.Destroy(customer); err != nil {
		return err
	}

	return c.Render(http.StatusOK, r.JSON(customer))

}
