package actions

import (
	"fmt"
	"github.com/gobuffalo/buffalo"
	"github.com/gobuffalo/pop/v5"
	"github.com/gobuffalo/x/responder"
	"github.com/shipanther/trober/models"
	"net/http"
)

// This file is generated by Buffalo. It offers a basic structure for
// adding, editing and deleting a page. If your model is more
// complex or you need more than the basic implementation you need to
// edit this file.

// Following naming logic is implemented in Buffalo:
// Model: Singular (Yard)
// DB Table: Plural (yards)
// Resource: Plural (Yards)
// Path: Plural (/yards)
// View Template Folder: Plural (/templates/yards/)

// YardsResource is the resource for the Yard model
type YardsResource struct {
	buffalo.Resource
}

// List gets all Yards. This function is mapped to the path
// GET /yards
func (v YardsResource) List(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return fmt.Errorf("no transaction found")
	}

	yards := &models.Yards{}

	// Paginate results. Params "page" and "per_page" control pagination.
	// Default values are "page=1" and "per_page=20".
	q := tx.PaginateFromParams(c.Params())

	// Retrieve all Yards from the DB
	if err := q.All(yards); err != nil {
		return err
	}

	return responder.Wants("html", func(c buffalo.Context) error {
		// Add the paginator to the context so it can be used in the template.
		c.Set("pagination", q.Paginator)

		c.Set("yards", yards)
		return c.Render(http.StatusOK, r.HTML("/yards/index.plush.html"))
	}).Wants("json", func(c buffalo.Context) error {
		return c.Render(200, r.JSON(yards))
	}).Wants("xml", func(c buffalo.Context) error {
		return c.Render(200, r.XML(yards))
	}).Respond(c)
}

// Show gets the data for one Yard. This function is mapped to
// the path GET /yards/{yard_id}
func (v YardsResource) Show(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return fmt.Errorf("no transaction found")
	}

	// Allocate an empty Yard
	yard := &models.Yard{}

	// To find the Yard the parameter yard_id is used.
	if err := tx.Find(yard, c.Param("yard_id")); err != nil {
		return c.Error(http.StatusNotFound, err)
	}

	return responder.Wants("html", func(c buffalo.Context) error {
		c.Set("yard", yard)

		return c.Render(http.StatusOK, r.HTML("/yards/show.plush.html"))
	}).Wants("json", func(c buffalo.Context) error {
		return c.Render(200, r.JSON(yard))
	}).Wants("xml", func(c buffalo.Context) error {
		return c.Render(200, r.XML(yard))
	}).Respond(c)
}

// Create adds a Yard to the DB. This function is mapped to the
// path POST /yards
func (v YardsResource) Create(c buffalo.Context) error {
	// Allocate an empty Yard
	yard := &models.Yard{}

	// Bind yard to the html form elements
	if err := c.Bind(yard); err != nil {
		return err
	}

	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return fmt.Errorf("no transaction found")
	}

	// Validate the data from the html form
	verrs, err := tx.ValidateAndCreate(yard)
	if err != nil {
		return err
	}

	if verrs.HasAny() {
		return responder.Wants("html", func(c buffalo.Context) error {
			// Make the errors available inside the html template
			c.Set("errors", verrs)

			// Render again the new.html template that the user can
			// correct the input.
			c.Set("yard", yard)

			return c.Render(http.StatusUnprocessableEntity, r.HTML("/yards/new.plush.html"))
		}).Wants("json", func(c buffalo.Context) error {
			return c.Render(http.StatusUnprocessableEntity, r.JSON(verrs))
		}).Wants("xml", func(c buffalo.Context) error {
			return c.Render(http.StatusUnprocessableEntity, r.XML(verrs))
		}).Respond(c)
	}

	return responder.Wants("html", func(c buffalo.Context) error {
		// If there are no errors set a success message
		c.Flash().Add("success", T.Translate(c, "yard.created.success"))

		// and redirect to the show page
		return c.Redirect(http.StatusSeeOther, "/yards/%v", yard.ID)
	}).Wants("json", func(c buffalo.Context) error {
		return c.Render(http.StatusCreated, r.JSON(yard))
	}).Wants("xml", func(c buffalo.Context) error {
		return c.Render(http.StatusCreated, r.XML(yard))
	}).Respond(c)
}

// Update changes a Yard in the DB. This function is mapped to
// the path PUT /yards/{yard_id}
func (v YardsResource) Update(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return fmt.Errorf("no transaction found")
	}

	// Allocate an empty Yard
	yard := &models.Yard{}

	if err := tx.Find(yard, c.Param("yard_id")); err != nil {
		return c.Error(http.StatusNotFound, err)
	}

	// Bind Yard to the html form elements
	if err := c.Bind(yard); err != nil {
		return err
	}

	verrs, err := tx.ValidateAndUpdate(yard)
	if err != nil {
		return err
	}

	if verrs.HasAny() {
		return responder.Wants("html", func(c buffalo.Context) error {
			// Make the errors available inside the html template
			c.Set("errors", verrs)

			// Render again the edit.html template that the user can
			// correct the input.
			c.Set("yard", yard)

			return c.Render(http.StatusUnprocessableEntity, r.HTML("/yards/edit.plush.html"))
		}).Wants("json", func(c buffalo.Context) error {
			return c.Render(http.StatusUnprocessableEntity, r.JSON(verrs))
		}).Wants("xml", func(c buffalo.Context) error {
			return c.Render(http.StatusUnprocessableEntity, r.XML(verrs))
		}).Respond(c)
	}

	return responder.Wants("html", func(c buffalo.Context) error {
		// If there are no errors set a success message
		c.Flash().Add("success", T.Translate(c, "yard.updated.success"))

		// and redirect to the show page
		return c.Redirect(http.StatusSeeOther, "/yards/%v", yard.ID)
	}).Wants("json", func(c buffalo.Context) error {
		return c.Render(http.StatusOK, r.JSON(yard))
	}).Wants("xml", func(c buffalo.Context) error {
		return c.Render(http.StatusOK, r.XML(yard))
	}).Respond(c)
}

// Destroy deletes a Yard from the DB. This function is mapped
// to the path DELETE /yards/{yard_id}
func (v YardsResource) Destroy(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return fmt.Errorf("no transaction found")
	}

	// Allocate an empty Yard
	yard := &models.Yard{}

	// To find the Yard the parameter yard_id is used.
	if err := tx.Find(yard, c.Param("yard_id")); err != nil {
		return c.Error(http.StatusNotFound, err)
	}

	if err := tx.Destroy(yard); err != nil {
		return err
	}

	return responder.Wants("html", func(c buffalo.Context) error {
		// If there are no errors set a flash message
		c.Flash().Add("success", T.Translate(c, "yard.destroyed.success"))

		// Redirect to the index page
		return c.Redirect(http.StatusSeeOther, "/yards")
	}).Wants("json", func(c buffalo.Context) error {
		return c.Render(http.StatusOK, r.JSON(yard))
	}).Wants("xml", func(c buffalo.Context) error {
		return c.Render(http.StatusOK, r.XML(yard))
	}).Respond(c)
}
