name: ci
on:
  pull_request:
  push:
    branches:
      - main
jobs:
  build-linux:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: harmon758/postgresql-action@v1
        with:
          postgresql version: "13"
          postgresql user: postgres
          postgresql password: postgres
      - run: |
          wget https://github.com/gobuffalo/buffalo/releases/download/v0.16.16/buffalo_0.16.16_Linux_x86_64.tar.gz
          tar -xvzf buffalo_0.16.16_Linux_x86_64.tar.gz
          ./buffalo test
  test-linux:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: docker build . -t test
