name: ci
on:
  pull_request:
  push:
    branches:
      - main
jobs:
  build-linux:
    name: Test
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

        ports:
          - 5432:5432
    steps:
      - uses: actions/checkout@v2
      - run: |
          wget --no-verbose https://github.com/gobuffalo/buffalo/releases/download/v0.16.21/buffalo_0.16.21_Linux_x86_64.tar.gz
          tar -xzf buffalo_0.16.21_Linux_x86_64.tar.gz
          export PATH="$PATH:$(pwd)"
          make test
      - uses: codecov/codecov-action@v1
  test-linux:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: docker build . -t test
  publish-sdk-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: cedx/setup-dart@v2
      - uses: actions/setup-java@v1
        with:
          java-version: "16"
      - name: Gen and verify sdk
        run: |
          export API_VERSION=0.0.1
          cd sdk;
          wget --no-verbose https://repo1.maven.org/maven2/org/openapitools/openapi-generator-cli/5.1.0/openapi-generator-cli-5.1.0.jar -O openapi-generator-cli.jar
          rm -rf trober_sdk; java -jar openapi-generator-cli.jar generate -i trober.yaml -c config.yaml -g dart-dio-next -o trober_sdk -p pubVersion=$API_VERSION
          cp LICENSE trober_sdk/LICENSE; echo "See https://github.com/bigpanther/trober/releases/tag/v$API_VERSION" > trober_sdk/CHANGELOG.md
          cd trober_sdk;
          echo 'homepage: https://bigpanther.ca/shipanther' >> pubspec.yaml
          sed -i 's/4.0.0-prev2/>=4.0.0 <5.0.0/g' pubspec.yaml
          sed -i 's/8.0.3/8.0.4/g' pubspec.yaml
          dart pub get; dart run build_runner build; dart format .;
          rm -rf .dart-tool .openapi-* .packages pubspec.lock
          pub publish --dry-run
