name: ci
on:
  pull_request:
  push:
    branches:
      - main
jobs:
  build-linux:
    name: Test
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

        ports:
          - 5432:5432
    steps:
      - uses: actions/checkout@v2
      - run: |
          wget https://github.com/gobuffalo/buffalo/releases/download/v0.16.21/buffalo_0.16.21_Linux_x86_64.tar.gz
          tar -xvzf buffalo_0.16.21_Linux_x86_64.tar.gz
          export PATH="$PATH:$(pwd)"
          make test
      - uses: codecov/codecov-action@v1
  test-linux:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: docker build . -t test
  publish-sdk-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: cedx/setup-dart@v2
      - uses: actions/setup-java@v1
        with:
          java-version: "13"
      - name: Gen and verify sdk
        run: |
          export API_VERSION=0.0.1
          cd sdk; rm -rf trober_sdk; dart pub get; dart pub run build_runner clean; dart pub run build_runner build --delete-conflicting-outputs; dart pub run cider --project-root=trober_sdk version $API_VERSION; dart format .; cp LICENSE trober_sdk/LICENSE; echo "The trober API" > trober_sdk/README.md; echo "See https://github.com/bigpanther/trober/releases/tag/v$API_VERSION" > trober_sdk/CHANGELOG.md
          cd trober_sdk; pub publish --dry-run
