name: ci
on:
  pull_request:
  push:
    branches:
      - main
jobs:
  build-linux:
    name: Test
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

        ports:
          - 5432:5432
    steps:
      - uses: actions/checkout@v3
      - run: |
          wget --no-verbose https://github.com/gobuffalo/cli/releases/download/v0.17.5/buffalo_0.17.5_Linux_x86_64.tar.gz
          tar -xzf buffalo_0.17.5_Linux_x86_64.tar.gz
          export PATH="$PATH:$(pwd)"
          make test
      - uses: codecov/codecov-action@v2
  test-linux:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: docker build . -t test
  publish-sdk-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dart-lang/setup-dart@v1
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: "16"
      - name: Gen and verify sdk
        run: |
          export API_VERSION=0.0.1
          cd sdk
          npm install @openapitools/openapi-generator-cli
          rm -rf trober_sdk
          npx @openapitools/openapi-generator-cli generate -i trober.yaml -c config.yaml -g dart-dio -o trober_sdk -p pubVersion=$API_VERSION
          cp LICENSE trober_sdk/LICENSE; echo "See https://github.com/bigpanther/trober/releases/tag/v$API_VERSION" > trober_sdk/CHANGELOG.md; cp README.md trober_sdk/README.md
          mv trober_sdk /tmp
          # publish complains about being gitignored
          cd /tmp/trober_sdk
          dart pub get
          dart run build_runner build
          rm -rf .dart-tool .openapi-* .packages pubspec.lock npm_modules .gitignore
          dart pub publish --dry-run
