name: release
on:
  push:
    branches:
      - "!*"
    tags:
      - "v*.*.*"
jobs:
  build:
    runs-on: ubuntu-latest
    name: release
    steps:
      - uses: actions/checkout@v2
      - run: echo "TROBER_VERSION_TO_SET=${GITHUB_REF##*/}" >> $GITHUB_ENV
      - run: echo "TROBER_MIN_VERSION_TO_SET=0.0.11" >> $GITHUB_ENV
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "trober-test"
          heroku_email: ${{secrets.HEROKU_DEPLOY_EMAIL}}
          usedocker: true
          docker_build_args: |
            TROBER_VERSION
            TROBER_COMMIT
            TROBER_MIN_VERSION
        env:
          TROBER_VERSION: ${TROBER_VERSION_TO_SET}
          TROBER_COMMIT: ${GITHUB_SHA}
          TROBER_MIN_VERSION: ${TROBER_MIN_VERSION_TO_SET}
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "trober"
          heroku_email: ${{secrets.HEROKU_DEPLOY_EMAIL}}
          usedocker: true
          docker_build_args: |
            TROBER_VERSION
            TROBER_COMMIT
            TROBER_MIN_VERSION
        env:
          TROBER_VERSION: ${TROBER_VERSION_TO_SET}
          TROBER_COMMIT: ${GITHUB_SHA}
          TROBER_MIN_VERSION: ${TROBER_MIN_VERSION_TO_SET}
  publish-sdk:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: cedx/setup-dart@v2
      - uses: actions/setup-java@v1
        with:
          java-version: "16"
      - name: Create & Publish package
        run: |
          export TROBER_VERSION=${GITHUB_REF##*/v}
          mkdir -p ~/.pub-cache
          cat <<EOF > ~/.pub-cache/credentials.json
          {
            "accessToken":"${{ secrets.PUB_DEV_ACCESS_TOKEN }}",
            "refreshToken":"${{ secrets.PUB_DEV_REFRESH_TOKEN }}",
            "tokenEndpoint":"https://accounts.google.com/o/oauth2/token",
            "scopes": [ "openid", "https://www.googleapis.com/auth/userinfo.email" ],
            "expiration": 1604987955347
          }
          EOF
          cd sdk;
          wget --no-verbose https://repo1.maven.org/maven2/org/openapitools/openapi-generator-cli/5.1.0/openapi-generator-cli-5.1.0.jar -O openapi-generator-cli.jar
          wget --no-verbose https://search.maven.org/remotecontent?filepath=com/bluetrainsoftware/maven/openapi-dart-generator/5.1/openapi-dart-generator-5.1.jar -O openapi-dart-generator.jar
          rm -rf trober_sdk; java -cp openapi-generator-cli.jar:openapi-dart-generator.jar org.openapitools.codegen.OpenAPIGenerator generate -i trober.yaml -c config.yaml -g dart2-api -o trober_sdk -p pubVersion=$TROBER_VERSION
          cp LICENSE trober_sdk/LICENSE; echo "See https://github.com/bigpanther/trober/releases/tag/v$TROBER_VERSION" > trober_sdk/CHANGELOG.md
          cd trober_sdk;
          sed -i 's/4.0.0-prev3/>=4.0.0 <5.0.0/g' pubspec.yaml
          sed -i 's/4.0.0-prev1/4.0.0/g' pubspec.yaml
          sed -i 's/1.3.0/1.16.8/g' pubspec.yaml

          dart pub get; dart format .;
          rm -rf .dart-tool .openapi-* .packages pubspec.lock
          pub publish -f
          rm -rf ~/.pub-cache
