name: release
on:
  push:
    branches:
      - "!*"
    tags:
      - "v*.*.*"
jobs:
  build:
    runs-on: ubuntu-latest
    name: release
    steps:
      - uses: actions/checkout@v3
      - run: echo "TROBER_VERSION_TO_SET=${GITHUB_REF##*/}" >> $GITHUB_ENV
      - run: echo "TROBER_MIN_VERSION_TO_SET=0.0.14" >> $GITHUB_ENV
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "trober-test"
          heroku_email: ${{secrets.HEROKU_DEPLOY_EMAIL}}
          usedocker: true
          docker_build_args: |
            TROBER_VERSION
            TROBER_COMMIT
            TROBER_MIN_VERSION
        env:
          TROBER_VERSION: ${TROBER_VERSION_TO_SET}
          TROBER_COMMIT: ${GITHUB_SHA}
          TROBER_MIN_VERSION: ${TROBER_MIN_VERSION_TO_SET}
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "trober"
          heroku_email: ${{secrets.HEROKU_DEPLOY_EMAIL}}
          usedocker: true
          docker_build_args: |
            TROBER_VERSION
            TROBER_COMMIT
            TROBER_MIN_VERSION
        env:
          TROBER_VERSION: ${TROBER_VERSION_TO_SET}
          TROBER_COMMIT: ${GITHUB_SHA}
          TROBER_MIN_VERSION: ${TROBER_MIN_VERSION_TO_SET}
  publish-sdk:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dart-lang/setup-dart@v1
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: "16"
      - name: Create & Publish package
        env:
          PUB_DEV_ACCESS_TOKEN: ${{ secrets.PUB_DEV_ACCESS_TOKEN }}
          PUB_DEV_REFRESH_TOKEN: ${{ secrets.PUB_DEV_REFRESH_TOKEN }}
        run: |
          export TROBER_VERSION=${GITHUB_REF##*/v}
          cd sdk
          npm install @openapitools/openapi-generator-cli
          rm -rf trober_sdk
          npx @openapitools/openapi-generator-cli generate -i trober.yaml -c config.yaml -g dart-dio -o trober_sdk -p pubVersion=$TROBER_VERSION
          cp LICENSE trober_sdk/LICENSE
          echo "See https://github.com/bigpanther/trober/releases/tag/v$TROBER_VERSION" > trober_sdk/CHANGELOG.md
          cp README.md trober_sdk/README.md
          mv trober_sdk /tmp
          # publish complains about being gitignored
          cd /tmp/trober_sdk
          dart pub get; dart run build_runner build;
          rm -rf .dart-tool .openapi-* .packages pubspec.lock node_modules
          mkdir -p ~/.pub-cache
          cat <<EOF > $XDG_CONFIG_HOME/dart/pub-credentials.json
          {
            "accessToken":"$PUB_DEV_ACCESS_TOKEN",
            "refreshToken":"$PUB_DEV_REFRESH_TOKEN",
            "tokenEndpoint":"https://accounts.google.com/o/oauth2/token",
            "scopes": [ "openid", "https://www.googleapis.com/auth/userinfo.email" ],
            "expiration": 1604987955347
          }
          EOF
          dart pub publish -f
          rm -rf $XDG_CONFIG_HOME/dart/pub-credentials.json
