name: release
on:
  push:
    branches:
      - "!*"
    tags:
      - "v*.*.*"
jobs:
  build:
    runs-on: ubuntu-latest
    name: release
    steps:
      - uses: actions/checkout@v2
      - run: export API_VERSION=${GITHUB_REF##*/}
      - run: echo ${API_VERSION}
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "trober-test"
          heroku_email: ${{secrets.HEROKU_DEPLOY_EMAIL}}
          usedocker: true
          docker_build_args: |
            TROBER_VERSION
            TROBER_COMMIT
        env:
          TROBER_VERSION: ${API_VERSION}
          TROBER_COMMIT: ${GITHUB_SHA}
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "trober"
          heroku_email: ${{secrets.HEROKU_DEPLOY_EMAIL}}
          usedocker: true
          docker_build_args: |
            TROBER_VERSION
            TROBER_COMMIT
        env:
          TROBER_VERSION: ${API_VERSION}
          TROBER_COMMIT: ${GITHUB_SHA}
  publish-sdk:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: cedx/setup-dart@v2
      - uses: actions/setup-java@v1
        with:
          java-version: "13"
      - name: Create & Publish package
        run: |
          export API_VERSION=${GITHUB_REF##*/v}
          cd sdk; rm -rf trober_sdk; dart pub get; dart pub run build_runner clean; dart pub run build_runner build --delete-conflicting-outputs; dart pub run cider --project-root=trober_sdk version $API_VERSION; dart format .; cp LICENSE trober_sdk/LICENSE; echo "The trober SDK for dart. It provides a dio client for the trober API." > trober_sdk/README.md; echo "See https://github.com/bigpanther/trober/releases/tag/v$API_VERSION" > trober_sdk/CHANGELOG.md
          mkdir -p ~/.pub-cache
          cat <<EOF > ~/.pub-cache/credentials.json
          {
            "accessToken":"${{ secrets.PUB_DEV_ACCESS_TOKEN }}",
            "refreshToken":"${{ secrets.PUB_DEV_REFRESH_TOKEN }}",
            "tokenEndpoint":"https://accounts.google.com/o/oauth2/token",
            "scopes": [ "openid", "https://www.googleapis.com/auth/userinfo.email" ],
            "expiration": 1604987955347
          }
          EOF
          cd trober_sdk; pub publish -f
          rm -rf ~/.pub-cache
