package models_test

// AUTOGENERATED BY: HSM GEN

import (
	"testing"

	m "github.com/bigpanther/trober/models"
)

func TestIsValidCarrierType(t *testing.T) {
	var validVal = "Air"
	var inValidVal = "_someInvalidval_"
	if !m.IsValidCarrierType(validVal) {
		t.Fatalf("IsValidCarrierType(%q) should be true", validVal)
	}
	if m.IsValidCarrierType(inValidVal) {
		t.Fatalf("IsValidCarrierType(%q) should be false", inValidVal)
	}
}
