package models_test

// AUTOGENERATED BY: HSM GEN

import (
	"testing"

	m "github.com/bigpanther/trober/models"
)

func TestIsValidContainerType(t *testing.T) {
	var validVal = "Incoming"
	var inValidVal = "_someInvalidval_"
	if !m.IsValidContainerType(validVal) {
		t.Fatalf("IsValidContainerType(%q) should be true", validVal)
	}
	if m.IsValidContainerType(inValidVal) {
		t.Fatalf("IsValidContainerType(%q) should be false", inValidVal)
	}
}
