package models_test

// AUTOGENERATED BY: HSM GEN

import (
	"testing"

	m "github.com/bigpanther/trober/models"
)

func TestIsValidContainerSize(t *testing.T) {
	var validVal = "40ST"
	var inValidVal = "_someInvalidval_"
	if !m.IsValidContainerSize(validVal) {
		t.Fatalf("IsValidContainerSize(%q) should be true", validVal)
	}
	if m.IsValidContainerSize(inValidVal) {
		t.Fatalf("IsValidContainerSize(%q) should be false", inValidVal)
	}
}
