package models_test

// AUTOGENERATED BY: HSM GEN

import (
	"testing"

	m "github.com/bigpanther/trober/models"
)

func TestIsValidShipmentType(t *testing.T) {
	var validVal = "Incoming"
	var inValidVal = "_someInvalidval_"
	if !m.IsValidShipmentType(validVal) {
		t.Fatalf("IsValidShipmentType(%q) should be true", validVal)
	}
	if m.IsValidShipmentType(inValidVal) {
		t.Fatalf("IsValidShipmentType(%q) should be false", inValidVal)
	}
}
