package models

// AUTOGENERATED BY: HSM GEN

// ShipmentType represents the ShipmentType enum
type ShipmentType string

const (
	// ShipmentTypeIncoming represents Incoming ShipmentType
	ShipmentTypeIncoming ShipmentType = "Incoming"
	// ShipmentTypeOutGoing represents OutGoing ShipmentType
	ShipmentTypeOutGoing ShipmentType = "OutGoing"
)

var allowedShipmentType [2]ShipmentType = [2]ShipmentType{
	ShipmentTypeIncoming,
	ShipmentTypeOutGoing,
}

// String returns the string representation of
func (k ShipmentType) String() string {
	return string(k)
}

// IsValidShipmentType validates if the input is a ShipmentType
func IsValidShipmentType(s string) bool {
	t := ShipmentType(s)
	return ShipmentTypeIncoming == t || ShipmentTypeOutGoing == t
}
