package models

// AUTOGENERATED BY: HSM GEN

// ShipmentType represents the ShipmentType enum
type ShipmentType string

const (
	// ShipmentTypeInbound represents Inbound ShipmentType
	ShipmentTypeInbound ShipmentType = "Inbound"
	// Outbound represents Outbound ShipmentType
	Outbound ShipmentType = "Outbound"
)

var allowedShipmentType [2]ShipmentType = [2]ShipmentType{
	ShipmentTypeInbound,
	Outbound,
}

// String returns the string representation of
func (k ShipmentType) String() string {
	return string(k)
}

// IsValidShipmentType validates if the input is a ShipmentType
func IsValidShipmentType(s string) bool {
	t := ShipmentType(s)
	return ShipmentTypeInbound == t || Outbound == t
}
