package models_test

// AUTOGENERATED BY: HSM GEN

import (
	"testing"

	m "github.com/bigpanther/trober/models"
)

func TestIsValidShipmentStatus(t *testing.T) {
	var validVal = "Unassigned"
	var inValidVal = "_someInvalidval_"
	if !m.IsValidShipmentStatus(validVal) {
		t.Fatalf("IsValidShipmentStatus(%q) should be true", validVal)
	}
	if m.IsValidShipmentStatus(inValidVal) {
		t.Fatalf("IsValidShipmentStatus(%q) should be false", inValidVal)
	}
}
