package models_test

// AUTOGENERATED BY: HSM GEN

import (
	"testing"

	m "github.com/bigpanther/trober/models"
)

func TestIsValidShipmentSize(t *testing.T) {
	var validVal = "40ST"
	var inValidVal = "_someInvalidval_"
	if !m.IsValidShipmentSize(validVal) {
		t.Fatalf("IsValidShipmentSize(%q) should be true", validVal)
	}
	if m.IsValidShipmentSize(inValidVal) {
		t.Fatalf("IsValidShipmentSize(%q) should be false", inValidVal)
	}
}
