package models_test

// AUTOGENERATED BY: HSM GEN

import(
	"testing"

	m "github.com/bigpanther/trober/models"
)

func TestIsValidTenantType(t *testing.T) {
	var validVal = "System"
	var inValidVal = "_someInvalidval_"
	if !m.IsValidTenantType(validVal) {
		t.Fatalf("IsValidTenantType(%q) should be true", validVal)
	}
	if m.IsValidTenantType(inValidVal) {
		t.Fatalf("IsValidTenantType(%q) should be false", inValidVal)
	}
}
