package models_test

// AUTOGENERATED BY: HSM GEN

import(
	"testing"

	m "github.com/bigpanther/trober/models"
)

func TestIsValidTerminalType(t *testing.T) {
	var validVal = "Rail"
	var inValidVal = "_someInvalidval_"
	if !m.IsValidTerminalType(validVal) {
		t.Fatalf("IsValidTerminalType(%q) should be true", validVal)
	}
	if m.IsValidTerminalType(inValidVal) {
		t.Fatalf("IsValidTerminalType(%q) should be false", inValidVal)
	}
}
