package models_test

// AUTOGENERATED BY: HSM GEN

import (
	"testing"

	m "github.com/bigpanther/trober/models"
)

func TestIsValidUserRole(t *testing.T) {
	var validVal = "SuperAdmin"
	var inValidVal = "_someInvalidval_"
	if !m.IsValidUserRole(validVal) {
		t.Fatalf("IsValidUserRole(%q) should be true", validVal)
	}
	if m.IsValidUserRole(inValidVal) {
		t.Fatalf("IsValidUserRole(%q) should be false", inValidVal)
	}
}
